### ISSUE TITLE
Members Should Link to Names and Not IDs

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#121]
When I click on a member name (whereever it's linked, be it in a news post, on a publication, etc.), it should take me that that member's page--but I'd like to use names for the pages and not IDs (or not just IDs).

![image](https://cloud.githubusercontent.com/assets/1621749/17938979/5d7f23d0-69f6-11e6-8fc0-c0ba18dd0cfe.png)

![image](https://cloud.githubusercontent.com/assets/1621749/17938970/4dceec4a-69f6-11e6-83f0-72d8fe4c221a.png)

**Comment by jonfroehlich** [comment]
So, to be clear, I want to be able to go to:
http://makeabilitylab.cs.washington.edu/people/jonfroehlich and be brought to the same page as http://makeabilitylab.cs.washington.edu/people/254. And I want to default to using names rather than ids.

**Comment by aileenzeng** [comment]
This issue ended up not actually getting resolved -- changes were originally made by adding a new field to `models.py`. This ended up breaking https://makeabilitylab-test.cs.washington.edu/, so the changes were scrapped. Some of the code from #357 is commented out.

This should be done by creating a function rather than another entry in the database.
