### ISSUE TITLE
Landing Page. Pub Section. Hook up Citation Link and Have Pop-Up Like Publications.html

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#324]
Hook up citation link and have citation pop-up like publications.html. Mockup below. Try to maximize code reuse between publications.html and landing page please.

![image](https://user-images.githubusercontent.com/1621749/34127785-39f169d2-e3f3-11e7-83ad-eb35646b77a6.png)

**Comment by lstearns86** [comment]
Got it working:
![image](https://user-images.githubusercontent.com/2319490/34132669-f0ca4fd6-e41e-11e7-8d85-3897271e7594.png)
I created a reusable jQuery class for when we need to display this elsewhere, although it isn't encapsulated as fully as I'd like (e.g., you need to call a few functions in the body load for each page that uses it, instead of just calling a single jQuery initializer). Something to improve in future versions.

**Comment by jonfroehlich** [comment]
Great, looking forward to seeing it!

**Comment by aileenzeng** [comment]
Hi @lstearns86, I'm @jonfroehlich's new summer intern. I'm starting to work on this website. This Issue looks solved--should we close it? Thanks.

**Comment by lstearns86** [comment]
Yes, this issue was solved in pull request #340. Closing it now.
