### ISSUE TITLE
Talk thumbnails on landing page are cut off

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#529]
Compare the thumbnails on the talks page vs. the landing page. On the landing page, the thumbnails are cut off on edges. This problem does not exist on talks page. (Note, however, that I much prefer the layout and rendering of the talks on the landing page. So, when we eventually create a Django snippet for this, it should be based on the landing page version).

Talks page:
![image](https://user-images.githubusercontent.com/1621749/43614922-2c47d2c4-966a-11e8-9af7-43807de0de2d.png)

Landing page:
![image](https://user-images.githubusercontent.com/1621749/43614937-47bbc664-966a-11e8-8262-6adeb711d2de.png)

**Comment by ShivenBhatt** [comment]
unfortunately, that's the only way I could come up with to keep the scaling working. The alternative is that the talks change height when they exceed the cropping box, but this makes things look worse.

We're in a bit of a tight spot since using the talks page layout makes our content misaligned with "see all" because of margins, but using my current landing page layout necessitates cropping so that we can scale and keep aspect ratio without increasing beyond the maximum 180px height for each item.

Any ideas?

**Comment by jonfroehlich** [comment]
OK, given your explanation, I think it's fine. Closing issue.
