### ISSUE TITLE
Add Making Maps Accessible and Putting Accessibility in Maps paper

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#583]
Once we get CSS working again on admin site, we need to add this paper. It's too painful to add content without CSS (and, in fact, you can't control author order given the widget that exists in the vanilla html, see below).

> Anke M. Brock, Jon E. Froehlich, João Guerreiro, Benjamin Tannert, Anat Caspi, Johannes Schöning, and Steve Landau. 2018. SIG: Making Maps Accessible and Putting Accessibility in Maps. In Extended Abstracts of the 2018 CHI Conference on Human Factors in Computing Systems (CHI EA '18). ACM, New York, NY, USA, Paper SIG03, 4 pages. DOI: https://doi-org.offcampus.lib.washington.edu/10.1145/3170427.3185373

![image](https://user-images.githubusercontent.com/1621749/44669748-a4a1de80-a9d5-11e8-86aa-74e62889bb9b.png)

**Comment by johnsonkuang** [comment]
Django's static files are not being loaded because they are not found in the server. 
[![Image from Gyazo](https://i.gyazo.com/81983b11713dacebceb7baf4e77f1c25.png)](https://gyazo.com/81983b11713dacebceb7baf4e77f1c25)

I think we should look in the database and maybe see where the command `collectstatic` looks and check if there are the files that django is looking for. It may also be that the docker permissions have changed and that Django does not have access to the `code/static` folder due to our changes from last time.

**Comment by jonfroehlich** [comment]
Done!

![image](https://user-images.githubusercontent.com/1621749/46210829-b503ec80-c2e6-11e8-92b6-d5652392d6da.png)
