### ISSUE TITLE
Oops, news title is broken on individual news item page

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#685]
![image](https://user-images.githubusercontent.com/1621749/47933756-a8992380-de92-11e8-85b9-0e8629ee3569.png)

**Comment by htadeusiak** [comment]
Not sure what happened, I'll fix it again.
![screen shot 2019-02-14 at 11 30 01 am](https://user-images.githubusercontent.com/33988444/52812262-ec7ff500-304b-11e9-9f6e-524ca97ff742.png)

**Comment by htadeusiak** [comment]
The if statements I added in the original PR were removed that's why this error pop up again. I fixed it, however, I feel like having the title there is bulky and not appealing. 
<img width="1439" alt="screen shot 2019-02-14 at 11 44 29 am" src="https://user-images.githubusercontent.com/33988444/52813588-f0f9dd00-304e-11e9-9107-803215f2d4dc.png">

One idea I had was to remove the title from the carousal or the whole carousal itself. Here's what those could look like:
<img width="1392" alt="screen shot 2019-02-14 at 11 55 05 am" src="https://user-images.githubusercontent.com/33988444/52813798-71204280-304f-11e9-8642-81695c577a7e.png">
<img width="1434" alt="screen shot 2019-02-14 at 11 49 00 am" src="https://user-images.githubusercontent.com/33988444/52813628-08d16100-304f-11e9-9c9e-16b135fb6edc.png">

Thoughts?

**Comment by jonfroehlich** [comment]
Yes but just for News page

**Comment by htadeusiak** [comment]
Which one? I prefer the one with the banner and no title.

**Comment by jonfroehlich** [comment]
Me too. Didn’t realize there were multiple options.
