### ISSUE TITLE
Long photo captions get cutoff

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#691]
![image](https://user-images.githubusercontent.com/1621749/48291566-d569af80-e42b-11e8-8bc3-1f020eb73536.png)

**Comment by jonfroehlich** [comment]
Not sure what the best fix is here...

**Comment by DDaiJ** [comment]
<img width="563" alt="screen shot 2019-01-16 at 4 37 01 pm" src="https://user-images.githubusercontent.com/37788907/51367744-e4f71b80-1aa0-11e9-9579-eefe393b188c.png">
<img width="563" alt="screen shot 2019-01-16 at 4 37 01 pm" src="https://user-images.githubusercontent.com/37788907/51367746-e6284880-1aa0-11e9-90bd-e6846c936c8b.png">

this is what it looks like right now, one is for short text and the second one is when the text length reaches maximum
I used inline-block for the caption display instead of the previous table-cell display

**Comment by DDaiJ** [comment]
<img width="499" alt="screen shot 2019-01-18 at 3 42 25 pm" src="https://user-images.githubusercontent.com/37788907/51418325-ae201480-1b37-11e9-948a-e88ba0b8f355.png">
<img width="523" alt="screen shot 2019-01-17 at 1 02 11 pm" src="https://user-images.githubusercontent.com/37788907/51418329-af514180-1b37-11e9-8ce2-f7134944c01f.png">

before and after

**Comment by DDaiJ** [comment]
The text length is set to have max_length=255 in the model
And the screenshot above shows how it would look when the text length reaches maximum. 

<img width="586" alt="screen shot 2019-01-18 at 4 36 13 pm" src="https://user-images.githubusercontent.com/37788907/51419419-3fdf5000-1b3f-11e9-8b3c-4eac653e9297.png">

Just in case you are interested, this is how it looks like when the text is shorter than maximum and longer than one-line text.

**Comment by jonfroehlich** [comment]
Great. Thanks!
